# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Update server branch
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www-sites/watermark.gofwd.co.za/watermarker/web/ && git fetch -a --prune && git checkout $CIRCLE_BRANCH && git pull origin $CIRCLE_BRANCH "
      - run:
          name: Check Env
          command: |
            ssh $SSH_USER@$SSH_HOST "env && nvm --version && npm -v && npm -v"
      - run:
          name: Build Service
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www-sites/watermark.gofwd.co.za/watermarker/web/ && npm install && npm run build"

workflows:
  version: 2
  deployment:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: /release-.*/



